/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.guacamole.auth.file;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import javax.xml.parsers.SAXParserFactory;
import org.apache.guacamole.xml.DocumentHandler;
import org.junit.Test;

/**
 * Test which verifies password validation of users defined within
 * user-mapping.xml, for each supported password encoding.
 */
public class AuthorizationTest {

    /**
     * A PBKDF2 hash of "secret" generated by the documented python3
     * one-liner, using 1000 iterations.
     */
    private static final String PBKDF2_SECRET = "pbkdf2-sha256$1000$"
            + "8WLkVbhEKSPZX+MlIARsuQ==$JvY61I9Y/JFE8tKKCx2vjIK1zyZ+p7ccd6TDpeGN4nQ=";

    /**
     * Parses the given user-mapping.xml contents exactly as
     * FileAuthenticationProvider does.
     *
     * @param xml
     *     The contents of a user-mapping.xml file.
     *
     * @return
     *     The parsed UserMapping.
     *
     * @throws Exception
     *     If the XML cannot be parsed.
     */
    private static UserMapping parse(String xml) throws Exception {
        UserMappingTagHandler handler = new UserMappingTagHandler();
        SAXParserFactory.newInstance().newSAXParser().parse(
                new ByteArrayInputStream(xml.getBytes(StandardCharsets.UTF_8)),
                new DocumentHandler("user-mapping", handler));
        return handler.asUserMapping();
    }

    /**
     * Parses a user-mapping.xml defining the single user "user" with the
     * given password and encoding, returning that user's Authorization.
     *
     * @param password
     *     The value of the password attribute.
     *
     * @param encoding
     *     The value of the encoding attribute, or null to omit it.
     *
     * @return
     *     The Authorization of the user "user".
     *
     * @throws Exception
     *     If the XML cannot be parsed.
     */
    private static Authorization user(String password, String encoding)
            throws Exception {
        return parse("<user-mapping><authorize username=\"user\" password=\""
                + password + "\""
                + (encoding != null ? " encoding=\"" + encoding + "\"" : "")
                + "/></user-mapping>").getAuthorization("user");
    }

    /**
     * Verifies that a PBKDF2 password accepts only the correct password.
     */
    @Test
    public void testPBKDF2() throws Exception {
        Authorization auth = user(PBKDF2_SECRET, "pbkdf2");
        assertTrue(auth.validate("user", "secret"));
        assertFalse(auth.validate("user", "Secret"));
        assertFalse(auth.validate("user", null));
        assertFalse(auth.validate("other", "secret"));
    }

    /**
     * Verifies that a malformed PBKDF2 password never authenticates, without
     * failing to parse the rest of the file.
     */
    @Test
    public void testMalformedPBKDF2() throws Exception {
        assertFalse(user("secret", "pbkdf2").validate("user", "secret"));
        assertFalse(user("pbkdf2-sha256$0$c2FsdA==$aGFzaA==", "pbkdf2").validate("user", "secret"));
        assertFalse(user("pbkdf2-sha256$1000$!!$aGFzaA==", "pbkdf2").validate("user", "secret"));
        assertFalse(user("", "pbkdf2").validate("user", ""));
    }

    /**
     * Verifies that the legacy plain, md5 and sha256 encodings are unchanged.
     */
    @Test
    public void testLegacyEncodings() throws Exception {

        assertTrue(user("secret", null).validate("user", "secret"));
        assertTrue(user("secret", "plain").validate("user", "secret"));
        assertFalse(user("secret", "plain").validate("user", "wrong"));

        assertTrue(user("5ebe2294ecd0e0f08eab7690d2a6ee69", "md5").validate("user", "secret"));
        assertFalse(user("5ebe2294ecd0e0f08eab7690d2a6ee69", "md5").validate("user", "wrong"));

        String sha256 = "2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b";
        assertTrue(user(sha256, "sha256").validate("user", "secret"));
        assertFalse(user(sha256, "sha256").validate("user", "wrong"));

    }

}
