/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.guacamole.net.auth;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import org.junit.Test;

/**
 * Test which verifies the behavior of PBKDF2PasswordHasher.
 */
public class PBKDF2PasswordHasherTest {

    /**
     * A hash of "correct horse ☃" generated by the python3 one-liner
     * documented for user-mapping.xml, using 600000 iterations.
     */
    private static final String PYTHON_HASH = "pbkdf2-sha256$600000$"
            + "ZzZv5+xerAxVFfPwc8song==$a2S/toMJqq9Kt8hvcriMiHfo1Twkc0bNaiV2Oc8KdKE=";

    /**
     * Verifies that hashing is deterministic for the same password, salt and
     * iteration count, and differs when the salt or iteration count differ.
     */
    @Test
    public void testDeterministic() {

        byte[] salt = "salt-one".getBytes(StandardCharsets.UTF_8);
        byte[] otherSalt = "salt-two".getBytes(StandardCharsets.UTF_8);

        byte[] hash = PBKDF2PasswordHasher.hash("password", salt, 1000);
        assertEquals(PBKDF2PasswordHasher.DEFAULT_LENGTH, hash.length);
        assertArrayEquals(hash, PBKDF2PasswordHasher.hash("password", salt, 1000));
        assertFalse(Arrays.equals(hash, PBKDF2PasswordHasher.hash("password", otherSalt, 1000)));
        assertFalse(Arrays.equals(hash, PBKDF2PasswordHasher.hash("password", salt, 1001)));

    }

    /**
     * Verifies the PBKDF2-HMAC-SHA256 output against the RFC 7914 section 11
     * test vector, proving this is the standard algorithm.
     */
    @Test
    public void testKnownVector() {
        byte[] hash = PBKDF2PasswordHasher.hash("passwd",
                "salt".getBytes(StandardCharsets.UTF_8), 1, 64);
        assertEquals((byte) 0x55, hash[0]);
        assertEquals((byte) 0xac, hash[1]);
        assertEquals((byte) 0x04, hash[2]);
        assertEquals((byte) 0x6e, hash[3]);
    }

    /**
     * Verifies that verify() accepts the correct password only.
     */
    @Test
    public void testVerify() {
        byte[] salt = PBKDF2PasswordHasher.generateSalt();
        byte[] hash = PBKDF2PasswordHasher.hash("password", salt, 1000);
        assertTrue(PBKDF2PasswordHasher.verify("password", salt, 1000, hash));
        assertFalse(PBKDF2PasswordHasher.verify("Password", salt, 1000, hash));
        assertFalse(PBKDF2PasswordHasher.verify(null, salt, 1000, hash));
    }

    /**
     * Verifies that encode() produces strings which verifyEncoded() accepts,
     * and that two encodings of the same password use different salts.
     */
    @Test
    public void testEncodeRoundTrip() {
        String encoded = PBKDF2PasswordHasher.encode("password", 1000);
        assertTrue(encoded.startsWith("pbkdf2-sha256$1000$"));
        assertTrue(PBKDF2PasswordHasher.verifyEncoded("password", encoded));
        assertFalse(PBKDF2PasswordHasher.verifyEncoded("wrong", encoded));
        assertFalse(encoded.equals(PBKDF2PasswordHasher.encode("password", 1000)));
    }

    /**
     * Verifies that a hash generated by the documented python3 one-liner is
     * accepted, including for a non-ASCII password.
     */
    @Test
    public void testPythonGeneratedHash() {
        assertTrue(PBKDF2PasswordHasher.verifyEncoded("correct horse ☃", PYTHON_HASH));
        assertFalse(PBKDF2PasswordHasher.verifyEncoded("correct horse", PYTHON_HASH));
    }

    /**
     * Verifies that malformed hash strings are rejected with an
     * IllegalArgumentException.
     */
    @Test
    public void testMalformed() {
        String[] malformed = {
            null,
            "",
            "abc",
            "pbkdf2-sha256$1000$c2FsdA==",
            "pbkdf2-sha1$1000$c2FsdA==$aGFzaA==",
            "pbkdf2-sha256$abc$c2FsdA==$aGFzaA==",
            "pbkdf2-sha256$0$c2FsdA==$aGFzaA==",
            "pbkdf2-sha256$-5$c2FsdA==$aGFzaA==",
            "pbkdf2-sha256$1000$$aGFzaA==",
            "pbkdf2-sha256$1000$c2FsdA==$",
            "pbkdf2-sha256$1000$not*base64$aGFzaA==",
            "pbkdf2-sha256$1000$c2FsdA==$aGFzaA==$extra"
        };
        for (String encoded : malformed) {
            try {
                PBKDF2PasswordHasher.verifyEncoded("password", encoded);
                fail("Malformed hash accepted: " + encoded);
            }
            catch (IllegalArgumentException e) {
                // Expected
            }
        }
    }

}
